finalLaunch/finalLaunch/urls.py
from django.conf.urls import include, url,static
from django.conf import settings
from django.contrib import admin
from homePage.views import homeView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','homePage.views.homeView',name='homeView'),
    url(r'^register/$','homePage.views.ajaxHomeView',name='ajaxHomeView'),
    url(r'^legal-disrupt/$','blogHome.views.ldHomeView',name='ldHomeView'),
    url(r'^legal-disrupt/articles/(?P<slug>[^\.]+)/$','blogHome.views.singleArticleView',name='singleArticleView'),
    url(r'^lawyer-registration/$','registerLawyer.views.lawyerRegisterView',name='lawyerRegisterView'),
    url(r'^lawyer-registration/thank-you/$','registerLawyer.views.lawyerThankView',name='lawyerThankView'),
    url(r'^legal-disrupt/articles/$','blogHome.views.allArticleView',name='allArticleView'),

]+ static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404='blogHome.views.handler404'

 

finalLaunch/blogHome/models.py
from datetime import datetime
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.db import models
from django.core.mail import send_mail


HTML_MESSAGE='<body style="vertical-align:middle;width:100%;"> \
	<table border="0" cellpadding="0" cellpadding="0" style="color: #333333;border-collapse:collapse;margin:0 auto;width:100%;">\
	 <tr style="width:100%; height:62px;text-align:center;"> <td style="text-align:center;"> <img style="width:100%;" \
	 src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/lawyered_newsletter_blogger_banner1.png"> </td> </tr> \
	 <tr style="text-align:center;"> <td style="letter-spacing:3px;padding-top:45px;color:#333333;"> <h3>THANK YOU FOR REGISTERING!\
	 </h3> </td> </tr> <tr style="text-align:center;"> <td style="text-align:center;padding-bottom:45px;"> <p style="color:#eb6a2b;font-style:italic;letter-spacing:1px;">We invite you to voice your opinion.<br> Share information,tips and advice to help readers tackle legal efficiency. </p> </td> </tr> <tr style="text-align:center;"> <td style="padding-bottom:20px;"> <p style="letter-spacing:1.2px;color:black"> Email us your story at <span style="color:#eb6a2b;">legaldisrupt@lawyered.in </span>along with a short<br> discription about yourself. </p> <p style="color:black;letter-spacing:1px;">We will get in touch with you at the earliest!</p> </td> </tr> <tr style="width:100%; height:62px;text-align:center;"> <td style="text-align:center;"> <img style="width:100%;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/lawyered_newsletter_blogger_banner2.png"> </td> </tr> <tr style="text-align:center;"> <td style="text-align:center;padding-top:20px;"> <a style="display:inline-block;" href="https://www.facebook.com/lawyered.in" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/facebook_.png"> </a> <a style="display:inline-block;" href="https://plus.google.com/108952108231921483693/about" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/google_.png"> </a> <a style="display:inline-block;" href="https://www.linkedin.com/company/lawyered" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/linkedin_.png"> </a> <a style="display:inline-block;" href="https://twitter.com/LawyeredTweets" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/twitter_.png"> </a> </td> </tr> </table> </body>'

	 
class Article(models.Model):
	article_title=models.CharField('Enter the title of your article',max_length=200,unique=True)
	article_slug=models.SlugField(max_length=100,unique=True)
	article_body=models.TextField('Enter body1 of article',)
	article_body1=models.TextField('Enter body2 of article',null=True,blank=True)
	middle_image=models.ImageField(upload_to='blogHome/articleImages',null=True,blank=True)
	cover_image=models.ImageField(upload_to='blogHone/articleImages')
	article_author=models.CharField('Enter author name',max_length=100)
	pub_date=models.DateTimeField('date published',default=datetime.now,blank=True)
	def get_absolute_url(self):
		return reverse('blogHome.views.',args=[str(self.article_slug)])
	def __str__(self):
		return self.article_title		

class InterestedPeople(models.Model):
	person_name=models.CharField(max_length=100,blank=False)
	person_email=models.EmailField(blank=False)
	person_city=models.CharField(max_length=30)
	phone_number=models.CharField(max_length=14)
	def __str__(self):
		return self.person_name
		
def send_email_to_interested_people(sender,instance,created,*args,**kwargs):
	if instance.person_email:
		send_mail('Welcome to Lawyered','','admin@lawyered.in',[instance.person_email],fail_silently=True,html_message=HTML_MESSAGE)
	else:
		pass	


post_save.connect(send_email_to_interested_people,sender=InterestedPeople)

finalLaunch/blogHome/forms.py
from django import forms
from .models import InterestedPeople

class ContactForm(forms.ModelForm):
	class Meta:
		model=InterestedPeople
		fields=('person_name','person_email','person_city','phone_number',)
		widgets={
			'person_name':forms.TextInput(
					attrs={'placeholder':'First name','class':'form-control'}
				),
			'person_email':forms.EmailInput(
					attrs={'placeholder':'Enter your email address','class':'form-control'}
				),
			'person_city':forms.TextInput(
					attrs={'placeholder':'Enter city','class':'form-control'}
				),
			'phone_number':forms.NumberInput(
					attrs={'placeholder':'Enter your 10-digit mobile number','class':'form-control',
					'type':'tel'
					}
				)
		}

finalLaunch/blogHome/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect,Http404
from .models import InterestedPeople,Article
from .forms import ContactForm



#All Articles.....................................................................
def allArticle():
	all_articles_obj=Article.objects.all()
	return all_articles_obj
	
#All Slugs........................................................................
def allSlug():
	all_articles_obj=Article.objects.all()
	all_articles_slugs=[x.article_slug for x in all_articles_obj]
	return all_articles_slugs
#Blog Home page handler............................................................
def ldHomeView(request):
	if request.method=='POST':
		form=ContactForm(data=request.POST)
		if form.is_valid():
			interestedPeople_obj=form.save()
			#interestedPeople_obj.save()
			popUp=1
			return render(request,'blogHome/blogHome.html',{'form':form,'popUp':popUp})
		else:
			print(form.errors)	
	else:
		form=ContactForm()

	all_articles=allArticle()
	latest_articles=all_articles[:5]	
	return render(request,'blogHome/blogHome.html',{'form':form,'latest_articles':latest_articles})			

#Single Blog page Handler..........................................................
def singleArticleView(request,slug):
	middle=None
	if request.method=='GET':

		all_articles_slugs=allSlug()
		if slug in all_articles_slugs:
			current_object=getCurrentObj(slug)
			
			if current_object.middle_image == None:
				middle=0
			else:
				middle=1	
		else:
			return HttpResponse('404 error')
	print(request.get_full_path())		
	return render(request,'singleArticle/singleArticle.html',{'current_object':current_object,'middle':middle,'current_path': request.get_full_path()})


def getCurrentObj(slug):
	all_slug=allSlug()
	index_current_slug=all_slug.index(slug)
	all_articles_obj=allArticle()
	current_object=all_articles_obj[index_current_slug]
	return current_object


#All Blog Page Handler..............................................................	
def allArticleView(request):
	all_articles_obj=allArticle()
	latest_articles3=all_articles_obj[:9]
	return render(request,'allArticles/allArticles.html',{'latest_articles':latest_articles3})


#404 Error Page Handler.............................................................
def handler404(request):
	return render(request,'404.html')	

finalLaunch/blogHome/templates/blogHome/blogHome.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en-us">
<head>
	<title>LAWYERED</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin"> 
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min1.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'blogHome/css/blogHome.css' %}">
</head>

<body>
  <header>
    <div class="container">
      <div class="header-nav">
        <span class="nav-ele"><a href="{% url 'homeView' %}"><img id="lawyered-link" src="{% static 'CommonImages/logo.png'%}"></a></span>
        <span class="nav-ele"><a href="{% url 'allArticleView' %}">ARTICLES</a></span>
      </div>
      <div class="header-middle">
        <img id="blog-logo" src="{% static 'CommonImages/ld.png' %}">
        <p class="p-middle">An initiative by <span><a id="lawyered-p" href="{% url 'homeView' %}">LAWYERED</a></span></p>
        <p class="p-bottom">Our featured blog provides transparent legal information</p>
      </div>
    </div>
  </header>

  <section id="our-need">
    <div class="container need-info">
      <h4><img class="comma-1" src="{% static 'blogHome/images/q1.png' %}">Law is freedom in its most controlled nature.<br>We all must abide by law, but it's unfair that we hardly understand law<img class="comma-2" src="{% static 'blogHome/images/q2.png' %}"></h4>
      <p>We, at Lawyered, understand Law and its complexity. It is important to understand the synergies
          of your buisness requirements and structure accordingly. We help you understand
          the compilance and process that are crucial for your buisness growth. sWe believe that this is not possible without active participation of lawyers and advisors. We invite you all to share your expertise and experiences.
      </p>  
      <div class="small-line"></div>
    </div>
  </section>

  <section id="form-area">
  <div class="container">
    <div class="row">
      <div class="col-sm-5 about-register">
        <h3>WANT TO SHARE YOUR STORY?</h3>
        <p>Our articles provide transparent and helpful information to consumers and business owners. If you have information, tips or advice to share, we’d like you to register with us.</p>
        <span>Register <img src="{% static 'CommonImages/arrow.png' %}"></span>
      </div>
      <div class="col-sm-6 register-form">
      
       <form class="form2" action="" method="post"  novalidate>
          {% csrf_token %}
          <div class="top-2f">
            <div class="form-group left-2">
              <label for="id_person_name">NAME</label><br>
              {{form.person_name}}
              <div class="errors" id="name-error">{{form.person_name.errors.as_text}}</div>
            </div>
          
            <div class="form-group right-2">
              <label for="id_person_email">E-MAIL</label><br>
              {{form.person_email}}
              <div class="errors" id="email-error">{{form.person_email.errors.as_text}}</div>
            </div>
          </div>
          <div class="bottom-2f">       
            <div class="form-group  left-2">
              <label for="id_person_city">CITY</label><br>
              {{form.person_city}}  
              <div class="errors" id="city-error">{{form.person_city.errors.as_text}}</div>         
            </div>
          
            <div class="form-group right-2">
              <label for="id_phone_number">PHONE NUMBER</label><br>
              {{form.phone_number}}
              <div class="errors" id="number-error">{{form.phone_number.errors.as_text}}</div>
            </div>
          </div>    
          <input class="btn btn-default form-input" id="button2" type="submit" value="submit"
          data-toggle="modal" >
          <!-- Modal -->
          <div id="myModal" class="modal fade" role="dialog">
          <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
              <p>Some text in the modal.</p>
            </div>
            <div class="modal-footer">
              <a href="{% url 'ldHomeView'%}" type="button" class="btn btn-default" data-dismiss="modal">Close</a>

            </div>
          </div>

        </form>
        
      </div>
    </div>
  </div>
  </section>

  <section id="articles-area">
    <div class="container articles-container">
      <div class="article-heading">
        <h3>ARTICLES</h3>
      </div>  
      <div class="small-line"></div>
    <div class="row">
    {% for article in latest_articles  %}

      <div class="col-sm-4">
        <div class="article-boxes">
          <a href="{% url 'singleArticleView' article.article_slug %}"><img class="article-images" src="{{article.cover_image.url}}"></a>
          <div class="article-body">
            <span><img src="{% static 'CommonImages/time.png' %}" height="15" width="15"></span>
            <span class="article-time">{{article.pub_date|time:"H:i"}}|</span>
            <span class="article-day">{{article.pub_date|date:"M d,Y"}}</span>
          
            <p class="article-body-p"><a href="{% url 'singleArticleView' article.article_slug %}">{{article.article_title}}</a></p>
            <span class="article-author">By {{article.article_author}}</span>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
  </section>

  <section id="tag-line">
    <div class="container">
      
      <h3>Legal Solution. Better. Easier. Faster.</h3>
      
    </div>
  </section>

 

  <section id="connect-us">
    <div class="container">
      <div class="connect-heading">
        <h4>CONNECT WITH US</h4>
        <div class="small-line"></div>
      </div>
      <div class="row footer-stuff">
        <div class="col-sm-4 col-md-4 footer-nav">
          <p>Give us a call!</p>
          <p>Call @<span class="p-span">+91-9898989989</span></p>
        </div>
        <div class="col-sm-4 footer-nav">
          <p>Have a question?</p>
          <p>Email us @<a class="p-span" href="">info@lawyered.in</a></p>
        </div>
        <div class="col-sm-4 footer-nav">
          <p>We are social @</p>
          <p>
            <span><a href="https://www.facebook.com/lawyered.in"><img src="{% static 'CommonImages/facebook_.png' %}" height="30" width="30"></a></span>
            <span><a href="https://twitter.com/LawyeredTweets"><img src="{% static 'CommonImages/twitter_.png' %}" height="30" width="30"></a></span>
            <span><a href="https://www.linkedin.com/company/lawyered"><img src="{% static 'CommonImages/linkedin_.png' %}" height="30" width="30"></a></span>
            <span><a href="https://plus.google.com/wm/capomaximo/108952108231921483693/posts/Qce5qcvUpBy"><img src="{% static 'CommonImages/google_.png' %}" height="30" width="30"></a></span>  
          </p>
        </div>
      </div>    
    </div>  
  </section> 
  
  <section id="copyright">
    <div class="container copyright-container">
      <span>Copyright @2015</span>
    </div>
  </section>
  

  <script type="text/javascript" src="{% static 'jquery/jquery-2.1.3.js' %}"></script>
  <script type="text/javascript" src="{% static 'blogHome/js/blogHome.js' %}"></script>
  <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js'%}"></script>
</body>