finalLaunch/finalLaunch/urls.py
from django.conf.urls import include, url,static
from django.conf import settings
from django.contrib import admin
from homePage.views import homeView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','homePage.views.homeView',name='homeView'),
    url(r'^register/$','homePage.views.ajaxHomeView',name='ajaxHomeView'),
    url(r'^legal-disrupt/$','blogHome.views.ldHomeView',name='ldHomeView'),
    url(r'^legal-disrupt/articles/(?P<slug>[^\.]+)/$','blogHome.views.singleArticleView',name='singleArticleView'),
    url(r'^lawyer-registration/$','registerLawyer.views.lawyerRegisterView',name='lawyerRegisterView'),
    url(r'^lawyer-registration/thank-you/$','registerLawyer.views.lawyerThankView',name='lawyerThankView'),
    url(r'^legal-disrupt/articles/$','blogHome.views.allArticleView',name='allArticleView'),

]+ static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404='blogHome.views.handler404'

 

finalLaunch/blogHome/models.py
from datetime import datetime
from django.core.urlresolvers import reverse
from django.db.models.signals import post_save
from django.db import models
from django.core.mail import send_mail


HTML_MESSAGE='<body style="vertical-align:middle;width:100%;"> \
	<table border="0" cellpadding="0" cellpadding="0" style="color: #333333;border-collapse:collapse;margin:0 auto;width:100%;">\
	 <tr style="width:100%; height:62px;text-align:center;"> <td style="text-align:center;"> <img style="width:100%;" \
	 src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/lawyered_newsletter_blogger_banner1.png"> </td> </tr> \
	 <tr style="text-align:center;"> <td style="letter-spacing:3px;padding-top:45px;color:#333333;"> <h3>THANK YOU FOR REGISTERING!\
	 </h3> </td> </tr> <tr style="text-align:center;"> <td style="text-align:center;padding-bottom:45px;"> <p style="color:#eb6a2b;font-style:italic;letter-spacing:1px;">We invite you to voice your opinion.<br> Share information,tips and advice to help readers tackle legal efficiency. </p> </td> </tr> <tr style="text-align:center;"> <td style="padding-bottom:20px;"> <p style="letter-spacing:1.2px;color:black"> Email us your story at <span style="color:#eb6a2b;">legaldisrupt@lawyered.in </span>along with a short<br> discription about yourself. </p> <p style="color:black;letter-spacing:1px;">We will get in touch with you at the earliest!</p> </td> </tr> <tr style="width:100%; height:62px;text-align:center;"> <td style="text-align:center;"> <img style="width:100%;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/lawyered_newsletter_blogger_banner2.png"> </td> </tr> <tr style="text-align:center;"> <td style="text-align:center;padding-top:20px;"> <a style="display:inline-block;" href="https://www.facebook.com/lawyered.in" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/facebook_.png"> </a> <a style="display:inline-block;" href="https://plus.google.com/108952108231921483693/about" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/google_.png"> </a> <a style="display:inline-block;" href="https://www.linkedin.com/company/lawyered" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/linkedin_.png"> </a> <a style="display:inline-block;" href="https://twitter.com/LawyeredTweets" target="_blank"> <img style="height:30px; width:30px;" src="https://s3-ap-northeast-1.amazonaws.com/teamlawyered/twitter_.png"> </a> </td> </tr> </table> </body>'

	 
class Article(models.Model):
	article_title=models.CharField('Enter the title of your article',max_length=200,unique=True)
	article_slug=models.SlugField(max_length=100,unique=True)
	article_body=models.TextField('Enter body1 of article',)
	article_body1=models.TextField('Enter body2 of article',null=True,blank=True)
	middle_image=models.ImageField(upload_to='blogHome/articleImages',null=True,blank=True)
	cover_image=models.ImageField(upload_to='blogHone/articleImages')
	article_author=models.CharField('Enter author name',max_length=100)
	pub_date=models.DateTimeField('date published',default=datetime.now,blank=True)
	def get_absolute_url(self):
		return reverse('blogHome.views.',args=[str(self.article_slug)])
	def __str__(self):
		return self.article_title		

class InterestedPeople(models.Model):
	person_name=models.CharField(max_length=100,blank=False)
	person_email=models.EmailField(blank=False)
	person_city=models.CharField(max_length=30)
	phone_number=models.CharField(max_length=14)
	def __str__(self):
		return self.person_name
		
def send_email_to_interested_people(sender,instance,created,*args,**kwargs):
	if instance.person_email:
		send_mail('Welcome to Lawyered','','admin@lawyered.in',[instance.person_email],fail_silently=True,html_message=HTML_MESSAGE)
	else:
		pass	


post_save.connect(send_email_to_interested_people,sender=InterestedPeople)

finalLaunch/registerLawyer/forms.py
from django import forms
from django.forms import extras
from .models import LawyerRegisterDetail
GENDER_CHOICES=(('Male','Male'),('Female','Female'),)
class lawyerRegisterForm(forms.ModelForm):
	gender=forms.ChoiceField(choices=GENDER_CHOICES,initial=GENDER_CHOICES[0][0], widget=forms.RadioSelect())
	class Meta:
		model = LawyerRegisterDetail
		fields='__all__'
		widgets={
			'first_name':forms.TextInput(
					attrs={'placeholder':'First name','type':'text','class':'form-control','name':'fname',
						'required autocomplete':'given-name'}
				),
			'last_name':forms.TextInput(
					attrs={'placeholder':'Last name','type':'text','class':'form-control','name':'lname',
						'required autocomplete':'family-name'}
				),
			'city_name':forms.TextInput(
					attrs={'placeholder':'Choose your city','type':'text','list':'city-list','class':'form-control'}
				),
			'company_name':forms.TextInput(
					attrs={'placeholder':'Enter company name','type':'text','class':'form-control'}
				),
			'date_of_birth':extras.SelectDateWidget(
					attrs={'class':'form-control date-picker required'},years=range(1905,2016)
				),
			'email':forms.EmailInput(
					attrs={'placeholder':'Enter your email address','type':'email','class':'form-control',
						'required autocomplete':'email'}
				),
			'phone_number':forms.NumberInput(
					attrs={'placeholder':'Enter your 10-digit mobile number','type':'tel','class':'form-control',
							'required autocomplete':'tel'
							,'required pattern':'^(?:(?:\+|0{0,2})91(\s*[\-]\s*)?|[0]?)?[789]\d{9}$'}
				),
			'state_bar_no':forms.TextInput(
					attrs={'placeholder':'State Bar where you originally enrolled','type':'text','class':'form-control'}
				),
			'bar_council_no':forms.TextInput(
					attrs={'placeholder':'Bar Council number','type':'text','class':'form-control'}
				)
			

		}
		exclude=['register_time']

finalLaunch/registerLawyer/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,HttpResponse
from .forms import  lawyerRegisterForm
from .models import LawyerRegisterDetail

# Create your views here.
def lawyerRegisterView(request):
	if request.method=='POST':
		reg_form=lawyerRegisterForm(request.POST)
		if reg_form.is_valid():
			print("xxxxxxxxxxxxxxxxxxxxxx")
			reg_obj=reg_form.save()
			return HttpResponseRedirect('/lawyer-registration/thank-you')	
		else:
			print(reg_form.errors)
	if request.method=='GET':
		reg_form=lawyerRegisterForm()
	return render(request,'registerLawyer/registerBlock.html',{'reg_form':reg_form})

def lawyerThankView(request):
	if request.method=='GET':
		return render(request,'registerLawyer/registerThankyou.html')

finalLaunch/registerLawyer/templates/registerLawyer/registerBase.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  	<meta charset="UTF-8">
  	<meta http-equiv="X-UA-Compatible" content="IE=Edge">
     <link href='http://fonts.googleapis.com/css?family=Arvo' rel='stylesheet' type='text/css'>
  	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu:regular,bold&subset=Latin">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min1.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'registerLawyer/css/registerLawyer.css' %}">
</head>
<body>
<header>
	<div class="container">
		<a href="{% url 'homeView' %}">
		<img id="lawyered-logo" src="{% static 'registerLawyer/images/logo.png' %}" height="50" width="155">
		</a>
	</div>
</header>
{% block registerLawyer %}
{% endblock %}
{% block thankYou %}
{% endblock %}



  <section id="connect-us">
    <div class="container">
      <div class="connect-heading">
        <h4>CONNECT WITH US</h4>
        <div class="small-line"></div>
      </div>
      <div class="row footer-stuff">
        <div class="col-sm-4 col-md-4 footer-nav">
          <p>Give us a call!</p>
          <p>Call @<span class="p-span">+91-9898989989</span></p>
        </div>
        <div class="col-sm-4 footer-nav">
          <p>Have a question?</p>
          <p>Email us @<a class="p-span" href="">info@lawyered.in</a></p>
        </div>
        <div class="col-sm-4 footer-nav">
          <p>We are social @</p>
          <p>
            <span><a href="https://www.facebook.com/lawyered.in"><img src="{% static 'CommonImages/facebook_.png' %}" height="30" width="30"></a></span>
            <span><a href="https://twitter.com/LawyeredTweets"><img src="{% static 'CommonImages/twitter_.png' %}" height="30" width="30"></a></span>
            <span><a href="https://www.linkedin.com/company/lawyered"><img src="{% static 'CommonImages/linkedin_.png' %}" height="30" width="30"></a></span>
            <span><a href="https://plus.google.com/wm/capomaximo/108952108231921483693/posts/Qce5qcvUpBy"><img src="{% static 'CommonImages/google_.png' %}" height="30" width="30"></a></span>
          </p>
        </div>
      </div>    
    </div>  
  </section>


  <section id="copyright">
    <div class="container copyright-container">
      <span>Copyright @2015</span>
    </div>
  </section>


</body>
</html>

finalLaunch/registerLawyer/templates/registerLawyer/registerBlock.html
{% extends "registerLawyer/registerBase.html" %}
{% load staticfiles %}
{% block registerLawyer %}

<section id="thrilled-us">
	<div class="container">
	<p class="thrilled-us-p">
		We are thrilled that you'd like to apply for early registration for <strong>LAWYERED</strong>.<br>Please fill out the form below and submit us your details!
	</p>
	</div>
</section>


<section id="form-section">
<div class="container all-form-stuff">
	<h5><strong>Fill in your details and register:</strong></h5>
	<form action="" method="post" id="register-form" role="form" novalidate>
		{% csrf_token %}
		<div class="cover-box">
	      <p class="input2 first">
			<label class="input-labels"for="id_first_name">NAME *</label><br>
			{{reg_form.first_name}}<br>
			<span class="errors fname-error">{{reg_form.first_name.errors.as_text}}<span>
		  </p>
		  <p class="input2 second" >	
			<label class="input-labels"  for="id_last_name"></label><br>
			{{reg_form.last_name}}<br>
			<span class="errors lname-error">{{reg_form.last_name.errors.as_text}}</span>
		  </p>
		</div>
		<div class="cover-box">
	      <p class="input2 first">
			<label class="input-labels" for="id_city_name">CITY *</label><br>
			{{reg_form.city_name}}<br>
			
			<datalist id="city-list">
				<option value="Delhi">
  				<option value="Gurgaon">
  				<option value="Mumbai">
  				<option value="Noida">
  				<option value="Chennai">
  				<option value="Bangalore">
			</datalist>
			<span class="errors city-error">{{reg_form.city_name.errors.as_text}}</span>
		  </p>
		  <p class="input2 second">	
			<label class="input-labels" for="id_company_name">COMPANY</label><br>
			{{reg_form.company_name}}<br>
			<span class="errors">{{reg_form.company_name.errors.as_text}}
		  </p>
		</div>
		<div class="cover-box">
	      <p class="input2 first">
			<label class="input-labels" for="id_date_of_birth">DATE OF BIRTH *</label><br>
			<span class="date-of-b"> {{reg_form.date_of_birth}}
			</span><br>
			<span class="errors dob-error">{{reg_form.date_of_birth.errors.as_text}}</span>
		  </p>
		  <p class="input2 second">	
			<label class="input-labels" for="id_gender">GENDER</label><br>
			{{reg_form.gender}}<br>
			<span class="errors">{{reg_form.gender.errors.as_text}}</span>
		  </p>
		</div>
		<div class="cover-box">
	      <p class="input2 first">
			<label class="input-labels" for="id_email">E-MAIL*</label><br>
			{{reg_form.email}}<br>
			<span class="errors email-error">{{reg_form.email.errors.as_text}}</span>
		  </p>
		  <p class="input2 second">
			<label class="input-labels" for="id_phone_number">PHONE NUMBER*</label><br>
			{{reg_form.phone_number}}<br>
			<span class="errors number-error">{{reg_form.phone_number.errors.as_text}}</span>
		  </p>
		</div>
		<div class="cover-box">
	      <p class="input2 first">
			<label class="input-labels" for="id_state_bar_no">STATE BAR</label><br>
			{{reg_form.state_bar_no}}<br>
			<span class="errors">{{reg_form.state_bar_no.errors.as_text}}</span>
		  </p>
		  <p class="input2 second">	
			<label class="input-labels" for="id_bar_council_no">BAR COUNCIL NUMBER</label><br>
			{{reg_form.bar_council_no}}<br>
			<span class="errors">{{reg_form.bar_council_no.errors.as_text}}</span>
		  </p>
		</div>
		<div class="big-line"></div>
		<p class="mandatory-fields">* Mandatory fields</p>
		<input class="btn btn-default form-input" id="button2" type="submit" value="register" name="submit">
	</form>
</div>	
</section>
<script type="text/javascript" src="{% static 'jquery/jquery-2.1.3.js' %}"></script>
<script type="text/javascript" src="{% static 'registerLawyer/js/registerLawyer.js' %}"></script>
{% endblock %}

finalLaunch/registerLawyer/templates/registerLawyer/registerThankyou.html
{% extends "registerLawyer/registerBase.html" %}
{% load staticfiles %}
{% block thankYou %}
	<section id="thank-you">
	<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.lawyered.in" data-text="Hello All" data-size="large">Tweet
  	</a>

		<h3>
         THANK YOU FOR REGISTERING WITH US!
		</h3>
		<p>our customer relation manager will contact you soon</p>
	</section>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
  </script>

{% endblock %}